# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenPower_RcppArmadillo <- function(A, v0, tol = 1e-6, maxit = 1e3L, verbose = 0L) {
    .Call('cpca_eigenPower_RcppArmadillo', PACKAGE = 'cpca', A, v0, tol, maxit, verbose)
}

eigenPower_Rcpp <- function(A, v0, tol = 1e-6, maxit = 1e3L, mode = 1L, verbose = 0L) {
    .Call('cpca_eigenPower_Rcpp', PACKAGE = 'cpca', A, v0, tol, maxit, mode, verbose)
}

eigenPower_RcppEigen <- function(A, tol = 1e-6, maxit = 1e3L, verbose = 0L) {
    .Call('cpca_eigenPower_RcppEigen', PACKAGE = 'cpca', A, tol, maxit, verbose)
}

numericNorm <- function(x) {
    .Call('cpca_numericNorm', PACKAGE = 'cpca', x)
}

numericProdMatVec <- function(mat, vec) {
    .Call('cpca_numericProdMatVec', PACKAGE = 'cpca', mat, vec)
}

numericMultVec <- function(x, a) {
    .Call('cpca_numericMultVec', PACKAGE = 'cpca', x, a)
}

